### ISSUE TITLE
Add Music Upload Feature

### ISSUE THREAD

**Issue by aashutoshrathi** [the-forty-two/the-boring-blog#15] opened 2018-01-23 18:44 UTC
This is necessary as most of the sites have dynamic link generation.

**Comment by anshumanv** [comment] 2018-01-23 18:45
Duplicate of #8

**Closed as completed by anshumanv** 2018-01-23 18:45 UTC
Labels: priority/high, feature

**Comment by aashutoshrathi** [comment] 2018-01-23 18:49
Oh sorry for inconvenience Mentor Sama.

**Comment by anshumanv** [comment] 2018-01-23 18:50
Shut the fuck up
